# Site settings
title: Code For Food
name: CodeForFood
locale: en_us
header-img: img/home-cover.png
email: jimit@outlook.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://jimgeek.github.io"
author:
  facebook:     Jimit1989
  twitter:      jimitnow
  google_plus:  JIMITSHAH
  github: JimGeek

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
